version: '3.4'

services:
  webapp:
    image: jhabpdemoidentityserver
    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Product
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=/https/8540925_jhabps.6mv6.com_iis/pfx-password.txt
      - ASPNETCORE_Kestrel__Certificates__Default__Path=//https/8540925_jhabps.6mv6.com_iis/8540925_jhabps.6mv6.com.pfx
    volumes:
      - G:\docker_volumns\https:/https