version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - G:\volumes\dbdata\mssql\:/var/opt/mssql
  
  identity-server:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.IdentityServer/Dockerfile
    depends_on:
      - sqlserver      
    volumes:
      - G:\volumes\ids4Log:/app/Logs
  
  my-demo:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.HttpApi.Host/Dockerfile
    depends_on:
      - sqlserver
      - identity-server
    volumes:
      - G:\volumes\hostLog:/app/Logs
