version: '3.4'

services:
  migrations:
    build:
      # context: ../../
      dockerfile: ./database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=MyDemo_Identity
      - MyDemo_DB=MyDemo_ModuleDb
      - SA_PASSWORD=Jh@123456
