version: '3.4'

services:
  redis:
    image: redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server

  migrations:
    build:
      # context: ../../
      dockerfile: ./database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=MyDemo_Identity
      - MyDemo_DB=MyDemo_ModuleDb
      - SA_PASSWORD=Jh@123456
  
  identity-server:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.IdentityServer/Dockerfile
    depends_on:
      - sqlserver      
      - redis      
    volumes:
      - G:\volumes\ids4Log:/app/Logs
      - G:\docker_volumns\https:/https
  
  my-demo:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.HttpApi.Host/Dockerfile
    depends_on:
      - sqlserver
      - identity-server
      - redis      
    volumes:
      - G:\volumes\hostLog:/app/Logs
      - G:\docker_volumns\https:/https
