version: '3.4'

services:
  redis:
    ports:
      - "6379:6379"
    restart: always


  sqlserver:
    environment:
      - SA_PASSWORD=Jh@123456
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: always


  identity-server:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hbmyyEVU
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/8540925_jhabps.6mv6.com_iis/8540925_jhabps.6mv6.com.pfx
      - ConnectionStrings__Default=Server=sqlserver;Database=MyDemo_Identity;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - ConnectionStrings__SqlServerCache=Server=sqlserver;Database=MyDemo_Cache;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - Redis__Configuration=redis
    ports:
      - "6302:443"
    restart: always

  my-demo:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hbmyyEVU
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/8540925_jhabps.6mv6.com_iis/8540925_jhabps.6mv6.com.pfx
      - ConnectionStrings__Default=Server=sqlserver;Database=MyDemo_ModuleDb;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - ConnectionStrings__AbpSettingManagement=Server=sqlserver;Database=MyDemo_Identity;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - ConnectionStrings__AbpPermissionManagement=Server=sqlserver;Database=MyDemo_Identity;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - ConnectionStrings__AbpAuditLogging=Server=sqlserver;Database=MyDemo_Identity;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - ConnectionStrings__SqlServerCache=Server=sqlserver;Database=MyDemo_Cache;Trusted_Connection=True;User=sa;Password=Jh@123456;Integrated Security=false
      - AuthServer__Authority=http://identity-server
      - Redis__Configuration=redis
    ports:
      - "6301:443"
    restart: always
  