version: '3.4'

services:
  redis:
    image: redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server
  
  identity-server:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.IdentityServer/Dockerfile
    depends_on:
      - sqlserver      
      - redis      
    volumes:
      - G:\volumes\ids4Log:/app/Logs
      - G:\docker_volumns\https:/https
  
  my-demo:
    build:
      # context: ../../
      dockerfile: ./host/MyDemo.HttpApi.Host/Dockerfile
    depends_on:
      - sqlserver
      - identity-server
      - redis      
    volumes:
      - G:\volumes\hostLog:/app/Logs
      - G:\docker_volumns\https:/https
